import { jsPDF } from 'jspdf'
import QRCode from 'qrcode'

/**
 * Generate invoice PDF with QR code
 * @param {Object} order - Order data from API
 * @returns {Promise<Blob>}
 */
export async function generateInvoicePDF(order) {
  // Create new PDF document
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let yPosition = 15

  // Header
  doc.setFont('Courier', 'bold')
  doc.setFontSize(20)
  doc.text('🍔 FOOD ORDER INVOICE', pageWidth / 2, yPosition, { align: 'center' })

  yPosition += 15

  // Order info
  doc.setFont('Courier', 'normal')
  doc.setFontSize(10)
  doc.text(`Order ID: ${order._id}`, 15, yPosition)
  yPosition += 7
  doc.text(`Date: ${new Date(order.createdAt).toLocaleString('vi-VN')}`, 15, yPosition)
  yPosition += 7
  doc.text(`Status: ${getStatusText(order.status)}`, 15, yPosition)

  yPosition += 12

  // Customer info section
  doc.setFont('Courier', 'bold')
  doc.setFontSize(11)
  doc.text('CUSTOMER INFORMATION', 15, yPosition)
  
  doc.setFont('Courier', 'normal')
  doc.setFontSize(10)
  yPosition += 8
  doc.text(`Name: ${order.customerName}`, 15, yPosition)
  yPosition += 6
  doc.text(`Email: ${order.customerEmail}`, 15, yPosition)
  yPosition += 6
  doc.text(`Phone: ${order.phone}`, 15, yPosition)
  yPosition += 6
  doc.text(`Address: ${order.address}`, 15, yPosition, { maxWidth: pageWidth - 30 })

  yPosition += 15

  // Items table header
  doc.setFont('Courier', 'bold')
  doc.setFontSize(10)
  doc.text('ITEMS', 15, yPosition)
  doc.text('QTY', 100, yPosition)
  doc.text('PRICE', 130, yPosition)
  doc.text('TOTAL', 170, yPosition, { align: 'right' })

  // Items
  yPosition += 8
  doc.setFont('Courier', 'normal')
  doc.setFontSize(9)

  order.items.forEach((item) => {
    const itemTotal = item.price * item.quantity
    doc.text(item.name.substring(0, 40), 15, yPosition, { maxWidth: 85 })
    doc.text(item.quantity.toString(), 100, yPosition)
    doc.text(`${item.price.toLocaleString()}đ`, 130, yPosition)
    doc.text(`${itemTotal.toLocaleString()}đ`, 170, yPosition, { align: 'right' })
    yPosition += 6
  })

  // Totals section
  yPosition += 8
  doc.setLineWidth(0.5)
  doc.line(15, yPosition, pageWidth - 15, yPosition)

  yPosition += 8
  doc.setFont('Courier', 'bold')
  doc.setFontSize(11)
  doc.text(`TOTAL: ${order.totalPrice.toLocaleString()}đ`, 170, yPosition, { align: 'right' })

  // Generate QR code
  yPosition += 20
  doc.setFont('Courier', 'bold')
  doc.setFontSize(10)
  doc.text('QR CODE - Scan để xem chi tiết', 15, yPosition)

  yPosition += 12
  try {
    const qrDataUrl = await QRCode.toDataURL(
      JSON.stringify({
        orderId: order._id,
        customerEmail: order.customerEmail,
        totalPrice: order.totalPrice,
        status: order.status,
        generatedAt: new Date().toISOString()
      }),
      { width: 100 }
    )
    doc.addImage(qrDataUrl, 'PNG', 35, yPosition, 50, 50)
    yPosition += 55
  } catch (err) {
    console.error('Error generating QR code:', err)
  }

  // Footer
  yPosition = pageHeight - 20
  doc.setFont('Courier', 'normal')
  doc.setFontSize(8)
  doc.text('Thank you for your order!', pageWidth / 2, yPosition, { align: 'center' })
  doc.text('Generated by Food Order System', pageWidth / 2, yPosition + 5, { align: 'center' })

  return doc
}

/**
 * Get readable status text
 * @param {string} status - Order status
 * @returns {string}
 */
function getStatusText(status) {
  const statusMap = {
    pending: '⏳ Chờ xử lý',
    confirmed: '✓ Xác nhận',
    preparing: '🔧 Chuẩn bị',
    ready: '📦 Sẵn sàng',
    shipping: '🚚 Đang giao',
    delivered: '✅ Hoàn thành',
    cancelled: '✕ Hủy'
  }
  return statusMap[status] || status
}

/**
 * Download PDF file
 * @param {jsPDF} doc - PDF document
 * @param {string} fileName - File name
 */
export function downloadPDF(doc, fileName) {
  doc.save(fileName || `invoice-${Date.now()}.pdf`)
}
